services:
    ezpublish_legacy.image_alias.cleaner:
        class: eZ\Publish\Core\MVC\Legacy\Image\AliasCleaner
        arguments:
            - "@Ibexa\\Bundle\\Core\\Imagine\\AliasCleaner"
            - "@Ibexa\\Core\\IO\\UrlRedecorator"
            - "@Ibexa\\Core\\FieldType\\Image\\IO\\Legacy"
        lazy: true
        public: false
