parameters:
    # Below default parameters, to be defined in ezpublish/config/config.yml

    ezpublish_legacy.enabled: true
    ezpublish_legacy.root_dir: "%kernel.project_dir%/ezpublish_legacy"
    ezpublish.default_router.legacy_aware_routes: ['_ezpublishLegacyTreeMenu', 'ezpublish_rest_', '_ezpublishPreviewContent', '_wdt', '_profiler', '_assetic']

    ezpublish_legacy.treemenu.controller.options: {}

    ezpublish_legacy.kernel_handler.cli.options:
        use-modules: true

    ezpublish_legacy.siteaccess_mapper.options: { fragment_path: "%fragment.path%" }
    ezpublish_legacy.configuration_mapper.options:
        imagemagick_enabled: "%ibexa.image.imagemagick.enabled%"
        imagemagick_executable_path: "%ibexa.image.imagemagick.executable_path%"
        imagemagick_executable: "%ibexa.image.imagemagick.executable%"
        imagemagick_filters: "%ibexa.image.imagemagick.filters%"

    ezpublish_legacy.config.default_scope: site

    # Non-supported packages will have url_alias_router to false
    ezpublish_legacy.setup_wizard.supported_packages: [ezdemo_site, ezdemo_site_clean]

services:
    ezpublish_legacy.kernel:
        alias: ezpublish_legacy.kernel.internal
        public: true

    ezpublish_legacy.kernel.internal:
        class: Closure
        public: true
        factory: ["@ezpublish_legacy.kernel.lazy_loader", buildLegacyKernel]
        arguments: ["@ezpublish_legacy.kernel_handler"]

    ezpublish_legacy.kernel.lazy_loader:
        class: eZ\Publish\Core\MVC\Legacy\Kernel\Loader
        public: true
        arguments:
            - "%ezpublish_legacy.root_dir%"
            - "%webroot_dir%"
            - "@event_dispatcher"
            - "@ezpublish_legacy.uri_helper"
            - "@Ibexa\\Core\\MVC\\Symfony\\SiteAccess"
            - "@?logger"
        calls:
            - [setContainer, ["@service_container"]]
            - [setRequestStack, ["@request_stack"]]

    ezpublish_legacy.rest.kernel_handler:
        class: ezpKernelRest
        public: true
        factory: ["@ezpublish_legacy.kernel.lazy_loader", buildLegacyKernelHandlerRest]
        arguments: [ezpKernelRest]

    ezpublish_legacy.kernel_handler.web:
        alias: ezpublish_legacy.kernel_handler.web.internal
        public: true

    ezpublish_legacy.kernel_handler.web.internal:
        class: ezpKernelHandler
        public: true
        factory: ["@ezpublish_legacy.kernel.lazy_loader", buildLegacyKernelHandlerWeb]
        arguments: [ezpKernelWeb]

    ezpublish_legacy.kernel_handler.treemenu:
        class: ezpKernelTreeMenu
        public: true
        factory: ["@ezpublish_legacy.kernel.lazy_loader", buildLegacyKernelHandlerTreeMenu]

    ezpublish_legacy.kernel_handler.cli:
        alias: ezpublish_legacy.kernel_handler.cli.internal
        public: true

    ezpublish_legacy.kernel_handler.cli.internal:
        class: eZ\Publish\Core\MVC\Legacy\Kernel\CLIHandler
        public: true
        factory: ["@ezpublish_legacy.kernel.lazy_loader", buildLegacyKernelHandlerCLI]

    ezpublish_legacy.kernel_handler:
        alias: ezpublish_legacy.kernel_handler.web
        public: true

    ezpublish_legacy.response_manager:
        class: eZ\Bundle\EzPublishLegacyBundle\LegacyResponse\LegacyResponseManager
        public: false
        arguments: ["@templating", "@ibexa.config.resolver", "@request_stack"]

    ezpublish_legacy.controller:
        class: eZ\Bundle\EzPublishLegacyBundle\Controller\LegacyKernelController
        public: true
        arguments:
            - "@ezpublish_legacy.kernel"
            - "@ibexa.config.resolver"
            - "@ezpublish_legacy.uri_helper"
            - "@ezpublish_legacy.response_manager"
            - "@ezpublish_legacy.templating.legacy_helper"
            - "@router"

    ezpublish_legacy.treemenu.controller:
        class: eZ\Bundle\EzPublishLegacyBundle\Controller\LegacyTreeMenuController
        public: true
        arguments:
            - "@ezpublish_legacy.kernel_handler.treemenu"
            - "@ezpublish_legacy.kernel.lazy_loader"
            - "%ezpublish_legacy.treemenu.controller.options%"
        parent: Ibexa\Core\MVC\Symfony\Controller\Controller

    ezpublish_legacy.rest.controller:
        class: eZ\Bundle\EzPublishLegacyBundle\Controller\LegacyRestController
        public: true
        arguments:
            - "@ezpublish_legacy.rest.kernel_handler"
            - "@ezpublish_legacy.kernel.lazy_loader"
        parent: Ibexa\Core\MVC\Symfony\Controller\Controller

    ezpublish_legacy.preview.controller:
        class: eZ\Bundle\EzPublishLegacyBundle\Controller\PreviewController
        public: true
        arguments:
            - '@ibexa.api.service.content'
            - '@ibexa.api.service.location'
            - "@http_kernel"
            - '@Ibexa\Core\Helper\ContentPreviewHelper'
            - "@security.authorization_checker"
            - '@Ibexa\Core\Helper\PreviewLocationProvider'
            - '@Ibexa\Core\MVC\Symfony\View\CustomLocationControllerChecker'
        calls:
            - [setConfigResolver, ["@ibexa.config.resolver"]]
        tags:
            - { name: controller.service_arguments }

    ibexa.controller.content.preview:
        alias: ezpublish_legacy.preview.controller
        public: true

    Ibexa\Core\MVC\Symfony\Controller\Content\PreviewController:
        alias: ezpublish_legacy.preview.controller
        public: true

    ezpublish_legacy.website_toolbar.controller:
        class: eZ\Bundle\EzPublishLegacyBundle\Controller\WebsiteToolbarController
        public: true
        parent: Ibexa\Core\MVC\Symfony\Controller\Controller
        arguments:
            - "@templating.engine.eztpl"
            - "@ibexa.api.service.content"
            - "@ibexa.api.service.location"
            - "@security.authorization_checker"
            - "@Ibexa\\Core\\Helper\\ContentPreviewHelper"
            - "$content.view_cache$"
            - "$content.ttl_cache$"
            - "$content.default_ttl$"
            - "@?security.csrf.token_manager"

    ezpublish_legacy.router:
        class: eZ\Bundle\EzPublishLegacyBundle\Routing\FallbackRouter
        public: false
        arguments: ["@ezpublish_legacy.url_generator", "@?request_context", "@?logger"]
        tags:
            - {name: router, priority: -255}
        lazy: true

    ezpublish_legacy.uri_helper:
        class: eZ\Publish\Core\MVC\Legacy\Kernel\URIHelper
        public: false

    ezpublish_legacy.url_generator:
        class: eZ\Bundle\EzPublishLegacyBundle\Routing\UrlGenerator
        public: false
        arguments: ["@ezpublish_legacy.kernel"]
        parent: Ibexa\Core\MVC\Symfony\Routing\Generator

    ezpublish_legacy.siteaccess_mapper:
        class: eZ\Bundle\EzPublishLegacyBundle\LegacyMapper\SiteAccess
        public: false
        arguments:
            - "@Ibexa\\Core\\MVC\\Symfony\\SiteAccess"
            - "%ezpublish_legacy.siteaccess_mapper.options%"
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.session_mapper:
        class: eZ\Bundle\EzPublishLegacyBundle\LegacyMapper\Session
        public: false
        arguments: ["@session.storage", "%ezpublish.session.attribute_bag.storage_key%", "@?session"]
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.session_storage_proxy:
        class: eZ\Publish\Core\MVC\Legacy\Session\LegacySessionStorage
        public: false
        arguments: ["@ezpublish_legacy.kernel", ~]

    ezpublish_legacy.session_handler_proxy:
        class: eZ\Publish\Core\MVC\Legacy\Session\LegacySessionProxy
        public: false
        arguments: ["@ezpublish_legacy.kernel", ~]

    ezpublish_legacy.configuration_mapper:
        class: eZ\Bundle\EzPublishLegacyBundle\LegacyMapper\Configuration
        public: false
        arguments:
            - "@ibexa.config.resolver"
            - "@ezpublish_legacy.switchable_http_cache_purger"
            - "@ezpublish_legacy.persistence_cache_purger"
            - "@Ibexa\\Core\\MVC\\Symfony\\Routing\\Generator\\UrlAliasGenerator"
            - "@ibexa.persistence.connection"
            - "@ezpublish_legacy.image_alias.cleaner"
            - "%ezpublish_legacy.configuration_mapper.options%"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.legacy_bundles_mapper:
        class: eZ\Bundle\EzPublishLegacyBundle\LegacyMapper\LegacyBundles
        public: false
        arguments:
            - { extensions: "%ezpublish_legacy.legacy_bundles_extensions%" }
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.persistence_cache_purger:
        class: eZ\Bundle\EzPublishLegacyBundle\Cache\PersistenceCachePurger
        public: false
        arguments:
            - "@ibexa.cache_pool"
            - "@Ibexa\\Core\\Persistence\\Cache\\LocationHandler"
            - '@Ibexa\Core\Persistence\Cache\Identifier\CacheIdentifierGeneratorInterface'
            - '%ezpublish_legacy.clear_all_spi_cache_on_symfony_clear_cache%'
            - '%ezpublish_legacy.clear_all_spi_cache_from_legacy%'
        tags:
            - { name: kernel.cache_clearer }
        lazy: true

    ezpublish_legacy.legacy_cache_purger:
        class: eZ\Bundle\EzPublishLegacyBundle\Cache\LegacyCachePurger
        public: false
        arguments:
            - "@ezpublish_legacy.kernel"
            - "@ezpublish_legacy.configuration_mapper"
            - "@filesystem"
            - "%ezpublish_legacy.root_dir%"
            - "@Ibexa\\Core\\MVC\\Symfony\\SiteAccess"
        tags:
            - { name: kernel.cache_clearer }
        lazy: true

    ezpublish_legacy.switchable_http_cache_purger:
        class: eZ\Bundle\EzPublishLegacyBundle\Cache\SwitchableHttpCachePurger
        public: false
        arguments: ["@ibexa.http_cache.purge_client"]

    ezpublish_legacy.content_exception_handler:
        class: eZ\Publish\Core\MVC\Legacy\EventListener\APIContentExceptionListener
        public: false
        arguments: ["@ezpublish_legacy.content_view_provider", "@ezpublish_legacy.location_view_provider", "@?logger"]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.config.resolver:
        class: eZ\Bundle\EzPublishLegacyBundle\DependencyInjection\Configuration\LegacyConfigResolver
        public: false
        arguments: ["@ezpublish_legacy.kernel", "%ezpublish_legacy.config.default_scope%"]
        lazy: true

    ezpublish_legacy.setup_wizard.configuration_converter:
        class: eZ\Bundle\EzPublishLegacyBundle\SetupWizard\ConfigurationConverter
        public: true
        arguments: ["@ezpublish_legacy.config.resolver", "@ezpublish_legacy.kernel", "%ezpublish_legacy.setup_wizard.supported_packages%"]

    # Image alias generator using legacy
    ezpublish_legacy.fieldType.ezimage.variation_service:
        class: eZ\Publish\Core\MVC\Legacy\Image\AliasGenerator
        public: false
        arguments: ["@ezpublish_legacy.kernel"]

    ezpublish_legacy.rest_listener:
        class: eZ\Bundle\EzPublishLegacyBundle\EventListener\RestListener
        public: false
        arguments: ["%ibexa.rest.csrf_token_intention%"]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.request_listener:
        class: eZ\Bundle\EzPublishLegacyBundle\EventListener\RequestListener
        public: false
        arguments: ["@ibexa.config.resolver", "@ibexa.api.repository", "@security.token_storage"]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.response_listener:
        class: eZ\Bundle\EzPublishLegacyBundle\EventListener\CsrfTokenResponseListener
        public: false
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.config_scope_listener:
        class: eZ\Bundle\EzPublishLegacyBundle\EventListener\ConfigScopeListener
        public: false
        arguments: ["@ezpublish_legacy.kernel.lazy_loader"]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.legacy_kernel_listener:
        class: eZ\Bundle\EzPublishLegacyBundle\EventListener\LegacyKernelListener
        public: false
        arguments: ["@event_dispatcher", "@ezpublish_legacy.kernel.lazy_loader"]
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish_legacy.legacy_bundles.extension_locator:
        class: eZ\Bundle\EzPublishLegacyBundle\LegacyBundles\LegacyExtensionsLocator
        public: true

    ezpublish_legacy.setup_listener:
        class: eZ\Bundle\EzPublishLegacyBundle\EventListener\SetupListener
        public: false
        arguments:
            - "@router"
            - "%ibexa.site_access.default%"
        tags:
            - { name: kernel.event_subscriber }
